name: Node.js CD to EC2
on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # This clears the warning

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
            
      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "3.6.132.160"
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/new-repo"

      - name: Restart Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "3.6.132.160"
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/new-repo
            npm install
            pm2 delete nodeapp || true
            pm2 start app.js --name nodeapp
